spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainingdb
    username: root
    password: Rohit@2000
  # below are optional properties
  # you may neglect, it is just for logging purpose
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    